version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001  

  discountdb:
    container_name: discountdb
    environment:
    - POSTGRES_USER=admin 
    - POSTGRES_PASSWORD=admin1234
    - POSTGRES_DB=DiscountDb
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin


  catalog.api:
    container_name: catalog.api
    image: gilmartmd/catalog_api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8080:8080"    
    depends_on:
      - catalogdb  
  
  basket.api:
    container_name: basket.api
    image: gilmartmd/basket_api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
    - basketdb
    ports:
    - "8081:8080"    
  
  discount.api:
      container_name: discount.api
      image: gilmartmd/discount_api
      build:
        context: .
        dockerfile: Services/Discount/Discount.API/Dockerfile
      environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234"
      depends_on:
      - discountdb
      ports:
      - "8082:8080"

  discount.grpc:
      container_name: discount.grpc
      image: gilmartmd/discount_grpc
      build:
        context: .
        dockerfile: Services/Discount/Discount.Grpc/Dockerfile
      environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234"
      depends_on:
      - discountdb
      ports:
      - "8083:8080"
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: